services:
  db:
    image: postgres:15-alpine
    container_name: minitrello-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: minitrello        
      POSTGRES_USER: postgres          
      POSTGRES_PASSWORD: postgres  
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minitrello-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: minitrello-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_USERNAME: postgres 
      DB_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/minitrello 
    ports:
      - "8080:8080"
    networks:
      - minitrello-network

  frotend:
    build:
      context: ./frotend
      dockerfile: Dockerfile
    container_name: minitrello-frotend
    restart: unless--stopped
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - minitrello-network


networks:
  minitrello-network:
    driver: bridge

volumes:
  postgres_data: